export './colors.dart';
export './lists.dart';
export './strings.dart';
export 'package:velocity_x/velocity_x.dart';
export 'package:flutter/material.dart';
export './images.dart';
export  'package:get/get.dart';
export  'package:get/get_core/src/get_main.dart';
export './firebase_consts.dart';